// Generated by https://quicktype.io

import { Field, ObjectType } from '@nestjs/graphql';

@ObjectType()
export class AssetUrl {
  @Field()
  descriptive: string;

  @Field()
  standard: string;
}

@ObjectType()
export class PaymentMethodCategory {
  @Field()
  identifier: string;

  @Field()
  name: string;

  @Field(() => AssetUrl)
  asset_urls: AssetUrl;
}

@ObjectType()
export class KlarnaSessionResponse {
  @Field()
  session_id: string;

  @Field()
  client_token: string;

  @Field(() => [PaymentMethodCategory])
  payment_method_categories: PaymentMethodCategory[];
}
