export default [
  'A.Kjærbede',
  'A7S',
  'Adrian Hammond',
  'Alpha Industries',
  'Ambitious',
  'Apple',
  'ARKK Copenhagen',
  'Armani',
  'Asics',
  'Audio-Technica',
  'Áhkká',
  'BaByliss',
  'Bally',
  'Barbour',
  'Beard Monkey',
  'Beatnik',
  'Bellroy',
  'Birkenstock',
  'Björn Borg',
  'Blundstone',
  'BOSS',
  'Braun',
  'Bread & Boxers',
  'Bulldog',
  'Calvin Klein Jeans',
  'Calvin Klein Underwear',
  'Calvin Klein',
  'Camper',
  'Carhartt WIP',
  'Casio',
  'CDLP',
  'Celly',
  'Champion Reverse Weave',
  'Champion',
  'CHPO',
  'Clarks Originals',
  'Clarks',
  'Colmar',
  'Columbia',
  'Converse',
  'Dapper Dan',
  'David Beckham',
  'DC Shoes',
  'Dedicated',
  'Denver',
  'Dick Moby',
  'Dickies',
  'Diesel',
  'Dr Martens',
  'Dr.Denim',
  'Ecooking',
  'Edwin Jagger',
  'Element',
  'Ellesse',
  'FILA',
  'Filippa K',
  'Filson',
  'Fossil',
  'Frank Dandy',
  'Fred Perry',
  'Fresh ́n Rebel',
  'G-Star',
  'Ga.Ma',
  'GABBA',
  'Gant Home',
  'Gant',
  'Gillette',
  'Goorin Bros',
  'GP',
  'Haglöfs',
  'Happy Socks',
  'Havaianas',
  'Helmut Lang',
  'Herschel',
  'Hestra',
  'Hi-Tec',
  'HUF',
  'Hugo Boss',
  'Human Scales',
  'Ingersoll 1892',
  'J.Lindeberg',
  'John Hatter & Co',
  'Jotex',
  'JUNK de LUXE',
  'Just For Men',
  'Just Junkies',
  'KAV',
  'Komono',
  'Kvarn',
  "L'Oréal Paris",
  'Lacoste',
  'Le Fix',
  'Le Specs',
  'Lee',
  'Legends',
  'Les Deux',
  "Levi's Made & Crafted",
  "Levi's",
  'Lyle & Scott',
  'Lyle Scott Casuals',
  'Malerifabrikken',
  'MenWith Skincare',
  'Meraki',
  'Merrell',
  'Mille Notti',
  'Modernist',
  'Morris',
  'Moser',
  'Moss & Noor',
  'Mouli',
  'Mountaineer Brand Premium',
  'Neuw',
  'New Balance',
  'New Era',
  'Nicce',
  'Nikben',
  'Nike',
  'Nivea',
  'Nividas',
  'Nudie Jeans',
  'Nõberu Of Sweden',
  'Oakley',
  'Oas',
  'OBH Nordica',
  'Oil Can Grooming',
  'Old Guys Rule',
  'Panasonic',
  'Peak Performance',
  'Philipp Plein',
  'Philips',
  'Pioneer',
  'Playboy Footwear',
  'Polo Ralph Lauren',
  'Pour',
  'Preach',
  'Puma',
  'Rains',
  'Raw Naturals',
  'Ray-Ban',
  'Recipe for men',
  'Red Wing Shoes',
  'Religion',
  'Remington',
  'Replay',
  'RM Williams',
  'Rock Off',
  'ROCKANDBLUE',
  'Saddler',
  'Sail Racing',
  'Sandays',
  'Sandqvist',
  'Schwarzkopf',
  'Scotch & Soda',
  'SHAKA',
  'Sneaker Lab',
  'Sneaky Steve',
  'Snoot',
  'Sons of Owen',
  'Sony',
  'Soulland',
  'Sovereign',
  'Speechless',
  'Stance',
  'STATE OF WOW',
  'Studio Total Active',
  'Studio Total Athleisure',
  'Studio Total Home',
  'Studio Total',
  'Stutterheim',
  'Sunpocket',
  'Superga',
  'The Classy Issue',
  'The People Vs.',
  'Thomas Sabo',
  'Tiger of Sweden',
  'Timberland',
  'Toki',
  'Tommy Hilfiger',
  'Tommy Jeans',
  'Topeco',
  'Toppik',
  'Tretorn',
  'Triumph Motorcycles',
  'Triwa',
  'Trust',
  'UGG',
  'Under Armour',
  'Upfront',
  'Uppercut Deluxe',
  'Urbanista',
  'Vagabond',
  'Vans',
  'Wahl',
  'Warrior Shanghai',
  'William Baxter',
  'William Strouch',
  'Wood Wood',
  'Woodbird',
  'Woolrich',
  'Zero°c',
  '8848 Altitude',
];
