export enum ProductReviewPermission {
  PUBLISH_REVIEW = 'PUBLISH_REVIEW',
  UPDATE_PRODUCT_REVIEW = 'UPDATE_PRODUCT_REVIEW',
  DELETE_PRODUCT_REVIEW = 'DELETE_PRODUCT_REVIEW',
  READ_PRODUCT_REVIEW = 'READ_PRODUCT_REVIEW',
}
